# -*- coding: utf-8 -*-
# *** Spyder Python Console History Log ***

## ---(Mon Feb  3 09:46:15 2025)---
runfile('C:/Users/GOLZARDM/.ipython/TDA/Mehed slop with hump.py', wdir='C:/Users/GOLZARDM/.ipython/TDA')

## ---(Fri Feb  7 22:01:13 2025)---
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-First run.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runcell(0, 'C:/Users/GOLZARDM/.spyder-py3/TDA-First run.py')
runcell(1, 'C:/Users/GOLZARDM/.spyder-py3/TDA-First run.py')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-First run.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
debugfile('C:/Users/GOLZARDM/.spyder-py3/TDA-First run.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-Second run.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-Third run.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-fourth run.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-Third run.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/Simple Slop  with Hamp using Riper - 2.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled3.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-Sixth run-more TDA features.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runcell(0, 'C:/Users/GOLZARDM/.spyder-py3/TDA-Fifth run.py')
runcell(0, 'C:/Users/GOLZARDM/.spyder-py3/TDA-Sixth run-more TDA features.py')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled5.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled6.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled7.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-Fifth run.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled5.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled6.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-Sixth run-more TDA features.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled8.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled7.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-Sixth run-more TDA features.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled5.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-7th-more features.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled7.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled9.py', wdir='C:/Users/GOLZARDM/.spyder-py3')

## ---(Sat Feb  8 13:45:57 2025)---
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-8th-more features.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-7th-more features.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-8th- EV features.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-7th-more features.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-Sixth run-more TDA features.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-9th-diagonal line-EV.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-Fifth run.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled0.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled1.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-Sixth run-more TDA features.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled2.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/Simple Slop  with Hamp using Riper - 2.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled3.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-All featres- HD.CSV.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled4.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-All featres- HD.CSV.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled5.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-All featres- HD.CSV.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled6.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-All features-2.CSV.py', wdir='C:/Users/GOLZARDM/.spyder-py3')

## ---(Fri Feb 14 12:05:10 2025)---
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled1.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled2.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled3.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled4.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled5.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled6.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
debugfile('C:/Users/GOLZARDM/.spyder-py3/untitled7.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
debugfile('C:/Users/GOLZARDM/.spyder-py3/untitled7.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled7.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
debugfile('C:/Users/GOLZARDM/.spyder-py3/untitled7.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled8.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
debugfile('C:/Users/GOLZARDM/.spyder-py3/untitled8.py', wdir='C:/Users/GOLZARDM/.spyder-py3')

## ---(Sat Feb 15 18:08:39 2025)---
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled0.py', wdir='C:/Users/GOLZARDM/.spyder-py3')

## ---(Sat Feb 15 19:34:38 2025)---
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled0.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-all features-RANSCAN.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.ipython/TDA/Mehed slop with hump.py', wdir='C:/Users/GOLZARDM/.ipython/TDA')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-all features-RANSCAN.py', wdir='C:/Users/GOLZARDM/.spyder-py3')

## ---(Sat Feb 15 19:37:06 2025)---
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled0.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runcell(1, 'C:/Users/GOLZARDM/.spyder-py3/untitled0.py')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled0.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-all features-RANSCAN.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled0.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runcell(1, 'C:/Users/GOLZARDM/.spyder-py3/untitled0.py')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled0.py', wdir='C:/Users/GOLZARDM/.spyder-py3')

## ---(Sun Feb 16 17:40:29 2025)---
!pip freeze
import sys
print("Python executable:", sys.executable)
print("Python version:", sys.version)
%runfile C:/Users/GOLZARDM/.spyder-py3/untitled0.py --wdir
%runfile 'C:/Users/GOLZARDM/.ipython/TDA/Mehed slop with hump.py' --wdir

## ---(Mon Feb 17 10:13:40 2025)---
runfile('C:/Users/GOLZARDM/.ipython/TDA/Mehed slop with hump.py', wdir='C:/Users/GOLZARDM/.ipython/TDA')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-All features-2.CSV.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
import sys
print('python executable:',sys.executable)
print('python version:',sys.version)
runcell(1, 'C:/Users/GOLZARDM/.ipython/TDA/Mehed slop with hump.py')
runfile('C:/Users/GOLZARDM/.spyder-py3/meshed slop with cavity_2.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.ipython/TDA/Mehed slop with hump.py', wdir='C:/Users/GOLZARDM/.ipython/TDA')
runcell(1, 'C:/Users/GOLZARDM/.ipython/TDA/Mehed slop with hump.py')
runfile('C:/Users/GOLZARDM/.ipython/TDA/Mehed slop with hump.py', wdir='C:/Users/GOLZARDM/.ipython/TDA')
runfile('C:/Users/GOLZARDM/.spyder-py3/meshed slop with cavity_2.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-All features-2.CSV.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-all features-RANSCAN.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled0.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-all features-DS with RANSCAN.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled0.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
debugfile('C:/Users/GOLZARDM/.spyder-py3/untitled0.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
debugfile('C:/Users/GOLZARDM/.spyder-py3/untitled1.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled1.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled2.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled3.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled2.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled5.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled6.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled6.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-All features-DSAL-Full CSV.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runcell(0, 'C:/Users/GOLZARDM/.spyder-py3/TDA-All features-DSAL-Full CSV.py')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-All features-DSAL-Full CSV.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/meshed slop with cavity_2.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.ipython/TDA/Mehed slop with hump.py', wdir='C:/Users/GOLZARDM/.ipython/TDA')
runfile('C:/Users/GOLZARDM/.spyder-py3/meshed slop with cavity_2.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-All features-DSAL-Full CSV.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled7.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runcell(1, 'C:/Users/GOLZARDM/.spyder-py3/untitled7.py')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled7.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runcell(1, 'C:/Users/GOLZARDM/.spyder-py3/untitled7.py')

## ---(Thu Feb 20 17:23:20 2025)---
runfile('C:/Users/GOLZARDM/.ipython/TDA/Mehed slop with hump.py', wdir='C:/Users/GOLZARDM/.ipython/TDA')

## ---(Fri Feb 21 10:42:40 2025)---
runfile('C:/Users/GOLZARDM/.spyder-py3/meshed slop with cavity_2.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/Mehed slop with hump.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
debugfile('C:/Users/GOLZARDM/.spyder-py3/Mehed slop with hump.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-feature extraction.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled1.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-feature extraction.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-All features-DSAL-Full CSV.py', wdir='C:/Users/GOLZARDM/.spyder-py3')

## ---(Mon Feb 24 19:22:59 2025)---
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-All features-DSAL-Full CSV.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-feature extraction.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled0.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled1.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-all features with graph.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled2.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled3.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-all features with graph-3.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled4.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled5.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled6.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled4.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-all features with graph-3.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled8.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runcell(1, 'C:/Users/GOLZARDM/.spyder-py3/untitled8.py')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled8.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runcell(1, 'C:/Users/GOLZARDM/.spyder-py3/untitled8.py')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled8.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runcell(0, 'C:/Users/GOLZARDM/.spyder-py3/untitled8.py')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled8.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runcell(1, 'C:/Users/GOLZARDM/.spyder-py3/untitled8.py')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled8.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/Features graphs using Python.py', wdir='C:/Users/GOLZARDM/.spyder-py3')

## ---(Wed Feb 26 11:41:07 2025)---
runfile('C:/Users/GOLZARDM/.spyder-py3/Features graphs using Python.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-all features with graph-3.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-All features-DSAL-Full CSV.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled0.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runcell(0, 'C:/Users/GOLZARDM/.spyder-py3/Feature graphs using Python-2.py')
runfile('C:/Users/GOLZARDM/.spyder-py3/Feature graphs using Python-2.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled1.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/Feature graphs using Python-2.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runcell(0, 'C:/Users/GOLZARDM/.spyder-py3/Feature graphs using Python-2.py')
runfile('C:/Users/GOLZARDM/.spyder-py3/Feature graphs using Python-2.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runcell(0, 'C:/Users/GOLZARDM/.spyder-py3/Feature graphs using Python-2.py')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-feature extraction.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/TDA-all features with graph-3.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/Feature graphs using Python-2.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runcell(0, 'C:/Users/GOLZARDM/.spyder-py3/Feature graphs using Python-2.py')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled1.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/Feature graphs using Python-2.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/untitled2.py', wdir='C:/Users/GOLZARDM/.spyder-py3')
runfile('C:/Users/GOLZARDM/.spyder-py3/Abnormalities_Features.py', wdir='C:/Users/GOLZARDM/.spyder-py3')

## ---(Thu Feb 27 15:27:52 2025)---
runfile('C:/Users/GOLZARDM/.spyder-py3/Abnormalities_Features.py', wdir='C:/Users/GOLZARDM/.spyder-py3')